### ISSUE TITLE
XML File Extension issue.

### ISSUE THREAD

**Issue by CyberCyclone** [me-ydv-5/camera-overlay#1]
You'll want to rename your LaunchScreen.storyboard.xml and Main.storyboard.xml files to remove the .xml extension as it breaks the storyboards in Xcode.

**Comment by ultrathlete** [comment]
That's a whoopsie, sorry I am super late. I just saw this issue, fixed it. 
https://github.com/me-ydv-5/camera-overlay/pull/2
